### ISSUE TITLE
Да се изгради система за мониториране на всички променливи на безжичните мрежи

### ISSUE THREAD

**Issue by ignisf** [ignisf/openfest-wifi#3]

**Comment by ignisf** [comment]
@zeridon е качил писанията си тук: https://github.com/zeridon/openfest-monitoring

Трябва да се тестват

**Comment by zeridon** [comment]
Добавена е и пълнофункционална конфигурация на централен колектор и клиент. Да се има в предвид че колектд работи върху UDP

**Comment by ignisf** [comment]
готово
